language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python setup.py install
script:
  - flake8 . --count 
after_success:
  - codecov
deploy:
  skip_cleanup: true
  skip_existing: true
  provider: pypi
  user: mcdonnellmt
  password:
    secure: pTnhLJiCPr8wTdMgh5yOLenu/rR+Zx8t0a12wqpACS/Oxx5YE1cIiKMOi7LgNFOgcq3m3DvJ2PEwLUVWOPxHmHSCwqFQKfXYahCXf1QcJV834+WoEiACgY4DYVMXQhossCvy3+rPKKV+k5BcHYOJZQul9AE9Dv/k6P4Nifw673dHG5N+ZgjHRY74CwKufPoKYXa+ZyUGYJDa5AOw/QfT2lxLiYwx/Fi4xqPLlPCxaRMQzRUf/WCI1PH6tGDG/8RaWGTe4k9JntJRL8O/h35+WV5mnCBx/xiTOCcHp6NpgKuX+lmiOYGCH0Z5+9N+CcptZgg9GDrXoRYLxVQk5pitwA/m2XP9GVFvqhmeSEtHHrWHPCSI3hJLqcP+RYc9fGiIojo9pqgVPa4fKfnFrwtGLcEyVMqb6FlWPjvhGJUGcbyE2T+9PZFE8DfHUzgVqSv4JRa4GK12JtI/oKyz/m3wHNA98pQiJMsAqcK3zWkKERVRipJHdLl1CJKVpqf+xra3gvgXF6lmpLGaWhiwtPbNvG3IJsufW/q67VmhA9ER5MZw/yyWdU/eGX6p6FNeUdz4aAifgF8LoX5eS/DtiVX6/VFedq+X6Nl95F7nodbHoI9Mnnq/eIj7VnqP/5bWfhWs0kKaHc4ha5exuoyTvPWuRl1s/EsAqKyGxKCfCibh518=
  on:
    tags: true
