name: pystog_ci_cd

env: {}

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Conda install deps
        shell: bash -l {0}
        run: |
          conda install --file requirements.txt --file requirements-dev.txt

      - name: Lint
        shell: bash -l {0}
        run: flake8 . --count
